changelog:
  categories:
    - title: Breaking Changes ✄
      labels: 
        - breaking-change
    - title: New Features 🥳
      labels:
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"